### ISSUE TITLE
first run pgxc_ctl report error: --home command line option doesn't work

### ISSUE THREAD

**Issue by wolftail** [postgres-x2/postgres-x2#84] opened 2015-05-11 14:54 UTC
after install, run follow:
pgxc_ctl --home /usr/local/system/postgresql/pgxc_home
report error:
Installing pgxc_ctl_bash script as /usr/local/system/postgresql/pgxc_home/pgxc_ctl_bash.
ERROR: File "/usr/local/system/postgresql/pgxc_home/pgxc_ctl.conf" not found or not a regular file. No such file or directory
Installing pgxc_ctl_bash script as /usr/local/system/postgresql/pgxc_home/pgxc_ctl_bash.
Reading configuration using /usr/local/system/postgresql/pgxc_home/pgxc_ctl_bash --home /usr/local/system/postgresql/pgxc_home --configuration /usr/local/system/postgresql/pgxc_home/pgxc_ctl.conf
Finished to read configuration.
ERROR: Number of elements in datanode master definitions are different datanodeNames and datanodeMasterDirs.  Check your configuration
ERROR: Found fundamental configuration error.
Segmentation fault

**Comment by koichi-szk** [comment] 2015-05-12 02:28
Does it happen only with --home option, right?   If so, it's a bug.  Will work on the fix.

Thank you.

Koichi

**Comment by shenlongxing** [comment] 2015-05-14 08:08
I do not think the cause is the command line option. Would you please post the pgxc_ctl.conf?

Thank you.

Shen Longxing

**Comment by koichi-szk** [comment] 2015-06-09 11:28
Koichi will look into it.

**Comment by asdliuquan** [comment] 2015-06-11 01:44
This bug have fixed by Shen Longxing. Please check the log of contrib/pgxc_ctl/config.c at 2015-05-17 19:19:20. So this issue can be closed.

**Comment by koichi-szk** [comment] 2015-06-23 06:24
Sorry, I'm afraid we don't have pull request or patch submission yet.   Please issue pull request if not yet.

**Comment by asdliuquan** [comment] 2015-06-24 06:16
I reviewed the github log, and found a bug has been fixed at 2015-05-17 without pull request. So the bug of pull request(#84) does not exist anymore, and no need any code modify.

**Comment by koichi-szk** [comment] 2015-06-24 08:12
Thanks a lot for the report.   Okay, will close this issue.

**Closed as completed by koichi-szk** 2015-06-24 08:12 UTC
Labels: bug
