### ISSUE TITLE
If GetAuxilliaryTransactionId return invalid transaction id, postgres will crash

### ISSUE THREAD

**Issue by DBInsight** [postgres-x2/postgres-x2#242] opened 2015-06-12 10:39 UTC
in pgxc_node_remote_commit, GetAuxilliaryTransactionId  can not gurantee it will return an valid xid, so the following `Assert(GlobalTransactionIdIsValid(remoteXactState.commitXid))' maybe crash.

it should report error, if it can not get an valid xid.

thoughts?

**Comment by koichi-szk** [comment] 2015-06-15 05:30
Agreed.   Could you provide a patch?

**Comment by DBInsight** [comment] 2015-06-15 07:17
no problem, but github has some problems  for me, when i edit online on my fork, i can't commit changes, 'commit changes' button can not click.

**Comment by koichi-szk** [comment] 2015-06-15 07:38
Did you use your forked repo?     Only a committer can commit to postgres-x2/postgres-x2 repo directly.   Before doing this, we run regression test and see if the patch is harmless or if it needs some more improvements.

To write your patch, please fork the repo to your space, do your code work and publish the pull request.

Thank you;

**Comment by wangchuanting** [comment] 2015-06-15 08:29
Did you use your forked repo?

yes.

**Comment by koichi-szk** [comment] 2015-06-15 09:16
Yes.   Of course I use the original repo to push the commit and also use
the original repo to test commit candidate.  This is committer's work.
 If you use a local copy the original repo, you have to share the patch
through e-mail or other means, not the pull request.   Patch is bit more
difficult to handle and track.

Regards;

---

Koichi Suzuki

2015-06-15 17:29 GMT+09:00 wangchuanting notifications@github.com:

**Comment by DBInsight** [comment] 2015-06-16 06:48
please review


@@ -1796,6 +1796,13 @@ pgxc_node_remote_commit(void)
 
 		if (!GlobalTransactionIdIsValid(remoteXactState.commitXid))
 			remoteXactState.commitXid = GetAuxilliaryTransactionId();
+			
+		if(!GlobalTransactionIdIsValid(remoteXactState.commitXid))
+		{
+			remoteXactState.status = RXACT_COMMIT_FAILED;
+			ereport(ERROR, (errcode(ERRCODE_INTERNAL_ERROR),
+					errmsg("failed to set commitXid for COMMIT PREPARED command")));
+		}
 	}
 
 	/*
@@ -1983,6 +1990,17 @@ pgxc_node_remote_abort(void)
 
 			if (!GlobalTransactionIdIsValid(remoteXactState.commitXid))
 				remoteXactState.commitXid = GetAuxilliaryTransactionId();
+				
+			/* Do not report error to avoid infinite loop of errors */
+			if (!GlobalTransactionIdIsValid(remoteXactState.commitXid))
+			{
+				ereport(WARNING, (errcode(ERRCODE_INTERNAL_ERROR),
+					errmsg("failed to set commitXid for ROLLBACK PREPARED command")));
+
+				return EOF;
+			}
+
+			Assert(GlobalTransactionIdIsValid(remoteXactState.commitXid));

**Comment by DBInsight** [comment] 2015-06-16 06:49
again for format.

@@ -1796,6 +1796,13 @@ pgxc_node_remote_commit(void)
 
 		if (!GlobalTransactionIdIsValid(remoteXactState.commitXid))
 			remoteXactState.commitXid = GetAuxilliaryTransactionId();
+			
+		if(!GlobalTransactionIdIsValid(remoteXactState.commitXid))
+		{
+			remoteXactState.status = RXACT_COMMIT_FAILED;
+			ereport(ERROR, (errcode(ERRCODE_INTERNAL_ERROR),
+					errmsg("failed to set commitXid for COMMIT PREPARED command")));
+		}
 	}
 
 	/*
@@ -1983,6 +1990,17 @@ pgxc_node_remote_abort(void)
 
 			if (!GlobalTransactionIdIsValid(remoteXactState.commitXid))
 				remoteXactState.commitXid = GetAuxilliaryTransactionId();
+				
+			/* Do not report error to avoid infinite loop of errors */
+			if (!GlobalTransactionIdIsValid(remoteXactState.commitXid))
+			{
+				ereport(WARNING, (errcode(ERRCODE_INTERNAL_ERROR),
+					errmsg("failed to set commitXid for ROLLBACK PREPARED command")));
+
+				return EOF;
+			}
+
+			Assert(GlobalTransactionIdIsValid(remoteXactState.commitXid));

**Comment by DBInsight** [comment] 2015-06-16 06:58
@@ -1796,6 +1796,13 @@ pgxc_node_remote_commit(void)
 
 		if (!GlobalTransactionIdIsValid(remoteXactState.commitXid))
 			remoteXactState.commitXid = GetAuxilliaryTransactionId();
+			
+		if(!GlobalTransactionIdIsValid(remoteXactState.commitXid))
+		{
+			remoteXactState.status = RXACT_COMMIT_FAILED;
+			ereport(ERROR, (errcode(ERRCODE_INTERNAL_ERROR),
+					errmsg("failed to set commitXid for COMMIT PREPARED command")));
+		}
 	}
 
 	/*
@@ -1983,6 +1990,17 @@ pgxc_node_remote_abort(void)
 
 			if (!GlobalTransactionIdIsValid(remoteXactState.commitXid))
 				remoteXactState.commitXid = GetAuxilliaryTransactionId();
+				
+			/* Do not report error to avoid infinite loop of errors */
+			if (!GlobalTransactionIdIsValid(remoteXactState.commitXid))
+			{
+				ereport(WARNING, (errcode(ERRCODE_INTERNAL_ERROR),
+					errmsg("failed to set commitXid for ROLLBACK PREPARED command")));
+
+				return EOF;
+			}
+
+			Assert(GlobalTransactionIdIsValid(remoteXactState.commitXid));
 
 			if (pgxc_node_send_gxid(connections[i], remoteXactState.commitXid))
 			{

**Comment by DBInsight** [comment] 2015-06-16 07:03
@@ -1796,6 +1796,13 @@ pgxc_node_remote_commit(void)
 
 		if (!GlobalTransactionIdIsValid(remoteXactState.commitXid))
 			remoteXactState.commitXid = GetAuxilliaryTransactionId();
+			
+		if(!GlobalTransactionIdIsValid(remoteXactState.commitXid))
+		{
+			remoteXactState.status = RXACT_COMMIT_FAILED;
+			ereport(ERROR, (errcode(ERRCODE_INTERNAL_ERROR),
+					errmsg("failed to set commitXid for COMMIT PREPARED command")));
+		}
 	}
 
 	/*
@@ -1983,6 +1990,17 @@ pgxc_node_remote_abort(void)
 
 			if (!GlobalTransactionIdIsValid(remoteXactState.commitXid))
 				remoteXactState.commitXid = GetAuxilliaryTransactionId();
+				
+			/* Do not report error to avoid infinite loop of errors */
+			if (!GlobalTransactionIdIsValid(remoteXactState.commitXid))
+			{
+				ereport(WARNING, (errcode(ERRCODE_INTERNAL_ERROR),
+					errmsg("failed to set commitXid for ROLLBACK PREPARED command")));
+
+				return EOF;
+			}
+
+			Assert(GlobalTransactionIdIsValid(remoteXactState.commitXid));
 
 			if (pgxc_node_send_gxid(connections[i], remoteXactState.commitXid))
 			{

**Comment by DBInsight** [comment] 2015-06-16 07:19
@@ -1796,6 +1796,13 @@ pgxc_node_remote_commit(void)
 
 		if (!GlobalTransactionIdIsValid(remoteXactState.commitXid))
 			remoteXactState.commitXid = GetAuxilliaryTransactionId();
+			
+		if(!GlobalTransactionIdIsValid(remoteXactState.commitXid))
+		{
+			remoteXactState.status = RXACT_COMMIT_FAILED;
+			ereport(ERROR, (errcode(ERRCODE_INTERNAL_ERROR),
+					errmsg("failed to set commitXid for COMMIT PREPARED command")));
+		}
 	}
 
 	/*
@@ -1983,6 +1990,17 @@ pgxc_node_remote_abort(void)
 
 			if (!GlobalTransactionIdIsValid(remoteXactState.commitXid))
 				remoteXactState.commitXid = GetAuxilliaryTransactionId();
+				
+			/* Do not report error to avoid infinite loop of errors */
+			if (!GlobalTransactionIdIsValid(remoteXactState.commitXid))
+			{
+				ereport(WARNING, (errcode(ERRCODE_INTERNAL_ERROR),
+					errmsg("failed to set commitXid for ROLLBACK PREPARED command")));
+
+				return EOF;
+			}
+
+			Assert(GlobalTransactionIdIsValid(remoteXactState.commitXid));
 
 			if (pgxc_node_send_gxid(connections[i], remoteXactState.commitXid))
 			{

**Comment by DBInsight** [comment] 2015-06-16 07:33
i can not paste patch, the format is completely mess;
and i can not attach the patch.

and i can not save edit on my forked repro.

**Comment by koichi-szk** [comment] 2015-06-16 09:13
Okay, besides to fix the problem could you send the whole file you rewrote
as embedded file to me?   Also please let me know what branch you used.

Thank you;

---

Koichi Suzuki

# Git and Github has many things you should be used to.

https://git-scm.com/book/en/v1/Getting-Started will be a good introduction
and is available with simplified Chinese.   Github tips will be found in

2015-06-16 16:33 GMT+09:00 DBInsight notifications@github.com:

**Comment by koichi-szk** [comment] 2015-06-16 09:13
Sorry, I couldn't find Github's handy TIPS page.   Will inform when found.

Thank you;

---

Koichi Suzuki

2015-06-16 18:13 GMT+09:00 Koichi Suzuki koichi.dbms@gmail.com:

**Comment by wangchuanting** [comment] 2015-06-16 12:03
DBInsight/1q2w3e4r5t    this is my account.you can sign in.thanks来自我的华为手机-------- 原始邮件 --------主题：Re: [postgres-x2] If GetAuxilliaryTransactionId return invalid transaction id, postgres will crash (#242)发件人：Koichi Suzuki 收件人：postgres-x2/postgres-x2 抄送：wangchuanting Okay, besides to fix the problem could you send the whole file you rewrote
as embedded file to me?   Also please let me know what branch you used.

Thank you;

---

Koichi Suzuki

# Git and Github has many things you should be used to.

https://git-scm.com/book/en/v1/Getting-Started will be a good introduction
and is available with simplified Chinese.   Github tips will be found in

2015-06-16 16:33 GMT+09:00 DBInsight notifications@github.com:

**Comment by DBInsight** [comment] 2015-09-07 07:13
Why we need  GetAuxilliaryTransactionId && pgxc_node_send_gxid to DN in pgxc_node_remote_commit?  as far as i known, there is no need to GetAuxilliaryTransactionId, so i want to remove GetAuxilliaryTransactionId and just sent down the "commit prepared" statement.

thoughts?

**Comment by koichi-szk** [comment] 2015-09-07 07:33
Right.   Because GTM requires GXID, we need to improve GTM protocol and
interface to do so.

---

Koichi Suzuki
https://www.linkedin.com/in/koichidbms

2015-09-07 16:13 GMT+09:00 DBInsight notifications@github.com:

**Comment by DBInsight** [comment] 2015-09-07 11:31
Now, we can not remove GetAuxilliaryTransactionId, because get snapshot need a xid, I just add a check to see if the xid is valid.

Wangchuanting/DBInsight

发件人: Koichi Suzuki [mailto:notifications@github.com]
发送时间: 2015年9月7日 15:34
收件人: postgres-x2/postgres-x2
抄送: Wangchuanting
主题: Re: [postgres-x2] If GetAuxilliaryTransactionId return invalid transaction id, postgres will crash (#242)

Right. Because GTM requires GXID, we need to improve GTM protocol and
interface to do so.

---

Koichi Suzuki
https://www.linkedin.com/in/koichidbms

2015-09-07 16:13 GMT+09:00 DBInsight <notifications@github.com<mailto:notifications@github.com>>:

**Comment by DBInsight** [comment] 2015-09-08 04:12
koichi-szk,
 i added a patch in yesterday's email reply, i want to know if you can see it or not?  and i found the patch is not attached in this issue,

i can not add attachments on the git web directly in company, only send patch through email is permitted

**Comment by koichi-szk** [comment] 2015-09-08 04:27
Yeah, github does not allow to upload arbitrary files.   You can folk your
own repository, make necessary changes, commit locally and post pull
request, which must be visible to me.

You can include whole patch file enclosed with lines ``` which presents
arbitrary text as literal, or you can e-mail the patch to me,
koichi.dbms@gmail.com.

Thank you very much;

---

Koichi Suzuki
https://www.linkedin.com/in/koichidbms

2015-09-08 13:12 GMT+09:00 DBInsight notifications@github.com:

**Comment by koichi-szk** [comment] 2015-09-08 08:15
The fix has been committed to relevant branches:

master: 57aa2e2b94f011bd71ddfa3ecf583eee890eb88b
REL1_2_STABLE: 2b2f536c2d87d6951079fd5b86544cd8af43fade
REL1_1_STABLE: 57260e01226ef1ddf9ffdaedce27c36b25e099bf

**Closed as completed by koichi-szk** 2015-09-08 08:15 UTC
Labels: bug
