### ISSUE TITLE
data inconsistent under concurrent update

### ISSUE THREAD

**Issue by 249159658** [postgres-x2/postgres-x2#266] opened 2015-07-27 06:08 UTC
host: centos 6.5
1 GTM,1 coordinator,4 datanode configured in one host.

postgres=# select \* from pgxc_node;
  node_name  | node_type | node_port | node_host | nodeis_primary | nodeis_preferre
d |   node_id  
-------------+-----------+-----------+-----------+----------------+----------------
--+-------------
 coordinator | C         |      5432 | localhost | f              | f  
  |  1416591337
 datanode1   | D         |      5433 | 127.0.0.1 | f              | f  
  |   888802358
 datanode2   | D         |      5434 | 127.0.0.1 | f              | f  
  |  -905831925
 datanode3   | D         |      5435 | 127.0.0.1 | f              | f  
  | -1894792127
 datanode4   | D         |      5436 | 127.0.0.1 | f              | f  
  | -1307323892
(5 rows)

postgres=# \d+ test
                         Table "public.test"
 Column |  Type   | Modifiers | Storage | Stats target | Description 
--------+---------+-----------+---------+--------------+-------------
 a      | integer |           | plain   |              | 
 b      | integer |           | plain   |              | 
 c      | integer |           | plain   |              | 
Indexes:
    "test_a_key" UNIQUE CONSTRAINT, btree (a)
Has OIDs: no
Distribute By: HASH(a)
Location Nodes: ALL DATANODES

postgres=# select \* from test;
 a |   b    |   c  
---+--------+--------
 1 | 130000 | 260000
(1 row)

While 20 concurrent update running, select return 2 records,see below:
postgres=# select xmin,xmax,\* from test ;
  xmin  |  xmax  | a |   b    |   c  
--------+--------+---+--------+--------
 126209 | 126213 | 1 | 114208 | 228416
 126206 | 126214 | 1 | 114210 | 228420
(2 rows)

each update is :
update test set b=b+1,c=c+2 where a = 1;
update test set b=b+1,c=c+2 where a = 1;
update test set b=b+1,c=c+2 where a = 1;
update test set b=b+1,c=c+2 where a = 1;
update test set b=b+1,c=c+2 where a = 1;
..........
repeat 10000  times.

update command:
./bin/psql -U pgxl -d postgres < test.sql > log1 &
./bin/psql -U pgxl -d postgres < test.sql > log2 &
./bin/psql -U pgxl -d postgres < test.sql > log3 &
./bin/psql -U pgxl -d postgres < test.sql > log4 &
./bin/psql -U pgxl -d postgres < test.sql > log5 &
./bin/psql -U pgxl -d postgres < test.sql > log6 &
./bin/psql -U pgxl -d postgres < test.sql > log7 &
./bin/psql -U pgxl -d postgres < test.sql > log8 &
./bin/psql -U pgxl -d postgres < test.sql > log9 &
./bin/psql -U pgxl -d postgres < test.sql > log10 &
./bin/psql -U pgxl -d postgres < test.sql > log11 &
./bin/psql -U pgxl -d postgres < test.sql > log12 &
./bin/psql -U pgxl -d postgres < test.sql > log13 &
./bin/psql -U pgxl -d postgres < test.sql > log14 &
./bin/psql -U pgxl -d postgres < test.sql > log15 &
./bin/psql -U pgxl -d postgres < test.sql > log16 &
./bin/psql -U pgxl -d postgres < test.sql > log17 &
./bin/psql -U pgxl -d postgres < test.sql > log18 &
./bin/psql -U pgxl -d postgres < test.sql > log19 &
./bin/psql -U pgxl -d postgres < test.sql > log20 &

my questoin is: why a unique key return 2 records?

**Comment by DBInsight** [comment] 2015-07-29 03:24
hi koichi-szk,can you give me a scenario which can cause inconsistency  if in commit flow:
1. we inform GTM firstly,  then commit on local node,
2. when other concurrent sessions get a snapshot, it does a check, if it find any xact exists on CN/DN, but not exists in gtm snapshot, it will wait this xact ended on local node; and then continue

**Comment by koichi-szk** [comment] 2015-07-29 03:26
When GTM is reported commit, GXID will be disappears from the snapshot
before the transaction is committed locally.   This means that the update
can be visible before the commit.   Instead, transactions report "START
PREPARING" before doing any local prepare and reports "COMMITTED" after all
the commits are done.

---

Koichi Suzuki
https://www.linkedin.com/in/koichidbms

2015-07-29 12:24 GMT+09:00 DBInsight notifications@github.com:

**Comment by DBInsight** [comment] 2015-07-29 03:39
#  This means that the update can be visible before the commit. 

this can not happen, because:
1. when other concurrent sessions get a snapshot, it would do a check, if it find any xact exists on CN/DN, but not exists in gtm snapshot, it will wait this xact ended on local node; and then continue

so other concurrent session can do nothing until the local commit done;

so "the update can be visible before the commit"  can not happen

**Comment by koichi-szk** [comment] 2015-07-29 03:49
Yes it can.   This has been observed more than one test.

If you say it cannot happen, what is the cause of this?   Pavan wrote
another patch (not applicable to XC directly) based on the same observation
and analysis and he reports it resolves the case.

---

Koichi Suzuki
https://www.linkedin.com/in/koichidbms

2015-07-29 12:39 GMT+09:00 DBInsight notifications@github.com:

**Comment by DBInsight** [comment] 2015-07-29 04:17
maybe misunderstand, i propose a new method:
1. we inform GTM firstly, then commit on local node,
2. when other concurrent sessions get a snapshot, it does a check, if it find any xact exists on CN/DN, but not exists in gtm snapshot, it will wait this xact ended on local node; and then continue

this method can resolve the V and V2 problem; 
select will not see V, because if V1 can update V, V must be committed, and in our method, if V commit on local, it must be already commit on gtm,

so V will not exists in select snapshot;

we found V and V2 problem in last year, and try many methods, and now we could not analysis any problem in our above new method.

we are very glad if you can give me a negative example.

thanks

**Comment by koichi-szk** [comment] 2015-07-29 04:18
I'm very strongly against it.  It can cause read inconsistency.

---

Koichi Suzuki
https://www.linkedin.com/in/koichidbms

2015-07-29 13:17 GMT+09:00 DBInsight notifications@github.com:

**Comment by koichi-szk** [comment] 2015-07-29 04:19
If reporting commit first to GTM before any local commit works fine, we
don't need GTM.

---

Koichi Suzuki
https://www.linkedin.com/in/koichidbms

2015-07-29 13:18 GMT+09:00 Koichi Suzuki koichi.dbms@gmail.com:

**Comment by DBInsight** [comment] 2015-07-29 04:20
it would be better to describes concurrent problem in time sequence:

session1 
xxx1
xxx2

seesion2
xxx1
xx2

session1
xx1
xx

**Comment by koichi-szk** [comment] 2015-07-29 04:25
Please give more detailed description, what transaction, what object, what
sequence, I mean exact order of each event, TRANSACTION BEGINS, TRANSACTION
READS, TRANSACTION WRITES, TRANSACTION PREPARE FOR COMMIT and TRANSACTION
COMMIT.   You need to show these event for each transaction and object
exactly in sequence.

Again, write consistency is not only the problem.  We need to provide both
read and write consistency to any transactions, at least for read-committed
isolation level.   Repeatable-read need another consideration of
"visibility timing" and serialization needs another consideration of
predicate lock.

Predicate lock needs some more thoughts (I believe local predicate lock
works globally as well).

Thank you;

---

Koichi Suzuki
https://www.linkedin.com/in/koichidbms

2015-07-29 13:20 GMT+09:00 DBInsight notifications@github.com:

**Comment by koichi-szk** [comment] 2015-07-29 04:26
These have been published more than five years ago to PG community and have
passed many people's review.

---

Koichi Suzuki
https://www.linkedin.com/in/koichidbms

2015-07-29 13:25 GMT+09:00 Koichi Suzuki koichi.dbms@gmail.com:

**Comment by koichi-szk** [comment] 2015-07-29 04:32
This shares the same background and cause as issue #256.  I put "duplicate" label to this.   Please move discussions to #256 thread and please review reports on this issue.

**Comment by galylee** [comment] 2015-07-29 07:20
I think @DBInsight his solution wont cause read inconsistent, because the new query will take a new snapshot from GTM, if the new query find the local uncommitted transaction(but actually GTM had marked it committed) but the transaction does not exit in the snapshot, the new query will wait until it committ locally. But this solution will cause every transaction to do a check.

**Comment by koichi-szk** [comment] 2015-08-03 07:02
I posted the following message to XL people.   I could not observe any inconsistencies in concurrent conflict update test with latest REL1_2_STABLE.    I suppose this is related to issue #254, OID duplicate in internal embedded functions.

Hope this is the real cause of the problems (with OID conflict, such side-effect can occur very easily).

With "go" and its "pq" package, Konstantin's test is not hard to run.   It's very helpful if anybody do the same test with different environment.

Regards;

**\* Posted Message ***

Hi,

I raun Konstaintin's test with XC (REL1_2_STABLE, without any dedicated fix) form more than an hour and didn't have any update conflict.   The following is the result.

```
---8<--------------------------------8<------------------------
[koichi@everest:inconsisitent_update_test]$ date

2015年  8月  3日 月曜日 13:40:50 CST

[koichi@everest:inconsisitent_update_test]$ go run runtest.go

1 : 0 -> 496880297 xid = 950188 count = 10000

^Cexit status 2

[koichi@everest:inconsisitent_update_test]$ date

2015年  8月  3日 月曜日 14:41:32 CST

[koichi@everest:inconsisitent_update_test]$
--->8----------------------------------->8---------------------
```

I used the following parameters:

```
    TRANSFER_CONNECTIONS = 10
    BALANCE_CONNECTIONS  = 10
```

I was wondering if previous analysis is correct.   Pavan's analysis suggests that TransactionIdDidCommit() may return true although the transaction commit has not been reached to GTM and GXID is still in the snapshot so that it is visible to other read transactions.

When I traced the code, I found that the target block has already been locked with EXCLUSIVE mode so that other read transaction cannot read it until the update has been done.

Then what is the candidate of the cause?   I noticed the conflict in embedded function OIDs in src/include/catalog.   This conflict exists as early as XC 1.1.   I found Pavan fixed this conflict in 9.5 merge, but not sure if it has been fixed in the version Konstantin used.

XC's REL1_2_STABLE has this fix.   This conflict may end up with calling wrong functions internally which can violate the lock and update wrong heap tuple.

I think XL should review and test this.

Regards;

**\* End of Posted Message ***

**Comment by koichi-szk** [comment] 2015-08-03 07:57
I ran the same test without OID duplicate fix.   As a result, no inconsistency observed.   I posted this to XL people as well.   Anyway, OID duplicate is not the cause.    Some of our fix might have worked.

Posted message is as follows:

**\* Posted Message ***

Further report on this:

I ran the same test without fixing OID duplicate in src/include/catalog and did not observe any in conflicts.  I ran about three million transactions (read and write) in about 15 minutes.

```
--->8-------------------------->8---------------------
[koichi@everest:inconsisitent_update_test]$ go run runtest.go
1 : 0 -> 505812819 xid = 2135 count = 10000
^Cexit status 2
[koichi@everest:inconsisitent_update_test]$ date
2015年  8月  3日 月曜日 15:35:15 CST
[koichi@everest:inconsisitent_update_test]$ go run runtest.go
1 : 0 -> 505812819 xid = 629401 count = 10000
^Cexit status 2
[koichi@everest:inconsisitent_update_test]$ go run runtest.go
1 : 0 -> 505812819 xid = 3079041 count = 10000
^Cexit status 2
[koichi@everest:inconsisitent_update_test]$ 
----8<------------------------------------8<----------------
```

Compared with Konstantin's result where he observed a conflict in about five thousand (write) transactions, I think the cause was not OID duplicate.

XC made so many fixes for stability this three months.   Some of these fixes might have worked.

Configuration is as follows:

```
--->8-------------------------->8---------------------
PGXC show config all
========= Postgres-XC configuration Common Info ========================
=== Overall ===
Postgres-XC owner: koichi
Postgres-XC user: koichi
Postgres-XC install directory: /home/koichi/pgxc
pgxc_ctl home: /home/koichi/pgxc_ctl
pgxc_ctl configuration file: /home/koichi/pgxc_ctl/pgxc_ctl_local.conf
pgxc_ctl tmpDir: /tmp
pgxc_ctl localTempDir: /tmp
pgxc_ctl log file: /home/koichi/pgxc_ctl/pgxc_log/11298_pgxc_ctl.log
pgxc_ctl configBackup: n
pgxc_ctl configBackupHost: none
pgxc_ctl configBackupFile: none
========= Postgres-XC configuration End Common Info ===================
====== Server: localhost =======
GTM Master: 
    Nodename: 'gtm', port: 20001, dir: '/home/koichi/pgxc/localnodes/gtm'    ExtraConfig: 'none', Specific Extra Config: 'none'
Coordinator Master: 
    Nodename: 'coord1', port: 20004, pooler port: 20010
    MaxWalSenders: 5, Dir: '/home/koichi/pgxc/localnodes/coord1'
    ExtraConfig: 'coordExtraConfig', Specific Extra Config: 'none'
    pg_hba entries ( '172.16.30.0/24' )
    Extra pg_hba: '172.16.30.0/24', Specific Extra pg_hba: 'none'
Coordinator Master: 
    Nodename: 'coord2', port: 20005, pooler port: 20011
    MaxWalSenders: 5, Dir: '/home/koichi/pgxc/localnodes/coord2'
    ExtraConfig: 'coordExtraConfig', Specific Extra Config: 'none'
    pg_hba entries ( '172.16.30.0/24' )
    Extra pg_hba: '172.16.30.0/24', Specific Extra pg_hba: 'none'
Datanode Master: 
    Nodename: 'datanode1', port: 20008
    MaxWALSenders: 5, Dir: '/home/koichi/pgxc/localnodes/dn1'
    ExtraConfig: 'none', Specific Extra Config: 'none'
    pg_hba entries ( '172.16.30.0/24' )
    Extra pg_hba: 'none', Specific Extra pg_hba: 'none'
Datanode Master: 
    Nodename: 'datanode2', port: 20009
    MaxWALSenders: 5, Dir: '/home/koichi/pgxc/localnodes/dn2'
    ExtraConfig: 'none', Specific Extra Config: 'none'
    pg_hba entries ( '172.16.30.0/24' )
    Extra pg_hba: 'none', Specific Extra pg_hba: 'none'
PGXC 
----8<------------------------------------8<----------------
```

Any input is welcome.

Best;
**\* End of Posted Message ***

**Comment by 249159658** [comment] 2015-08-04 02:53
@koichi-szk  Plaese set  synchronous_commit = off  in postgresql.conf.
then retry the test.

**Comment by koichi-szk** [comment] 2015-08-04 03:00
Hello;

Thanks a lot for the info.   Could you let me know the background why this
setting is needed?   Does it mean that synchronous commit does not cause
the inconsistency?

Best;

---

Koichi Suzuki
https://www.linkedin.com/in/koichidbms

2015-08-04 11:53 GMT+09:00 decai notifications@github.com:

**Comment by koichi-szk** [comment] 2015-08-04 04:55
I ran the same test with synchronous_commit = off for more than 30 minutes, where about 4.5 million transactions ran.   There are no in conflict observed.

synchronous_commit controls when to write commit record to WAL, which affects its behavior after the crash recovery.   If synchronous_commit is off, then we have some chance to lose some transactions committed just before the crash.   As long as the crash is not involved in the test, it sounds reasonable that we didn't have any difference.

Please write if there are any other configuration we should test.

Thanks.

Test result:

```
[koichi@everest:~]$ cd wk/inconsisitent_update_test/
[koichi@everest:inconsisitent_update_test]$ ls
init.sql  runtest.go
[koichi@everest:inconsisitent_update_test]$ go run runtest.go
1 : 0 -> 502392407 xid = 2323 count = 10000
^Cexit status 2
[koichi@everest:inconsisitent_update_test]$ date
2015年  8月  4日 火曜日 12:19:00 CST
[koichi@everest:inconsisitent_update_test]$ go run runtest.go
1 : 0 -> 502392407 xid = 76502 count = 10000
^Cexit status 2
[koichi@everest:inconsisitent_update_test]$ date
2015年  8月  4日 火曜日 12:49:48 CST
[koichi@everest:inconsisitent_update_test]$ go run runtest.go
1 : 0 -> 502392407 xid = 4648737 count = 10000
^Cexit status 2
[koichi@everest:inconsisitent_update_test]$ 
```

Settings:

```
PGXC show config all
========= Postgres-XC configuration Common Info ========================
=== Overall ===
Postgres-XC owner: koichi
Postgres-XC user: koichi
Postgres-XC install directory: /home/koichi/pgxc
pgxc_ctl home: /home/koichi/pgxc_ctl
pgxc_ctl configuration file: /home/koichi/pgxc_ctl/pgxc_ctl_local.conf
pgxc_ctl tmpDir: /tmp
pgxc_ctl localTempDir: /tmp
pgxc_ctl log file: /home/koichi/pgxc_ctl/pgxc_log/5792_pgxc_ctl.log
pgxc_ctl configBackup: n
pgxc_ctl configBackupHost: none
pgxc_ctl configBackupFile: none
========= Postgres-XC configuration End Common Info ===================
====== Server: localhost =======
GTM Master: 
    Nodename: 'gtm', port: 20001, dir: '/home/koichi/pgxc/localnodes/gtm'    ExtraConfig: 'none', Specific Extra Config: 'none'
Coordinator Master: 
    Nodename: 'coord1', port: 20004, pooler port: 20010
    MaxWalSenders: 5, Dir: '/home/koichi/pgxc/localnodes/coord1'
    ExtraConfig: 'coordExtraConfig', Specific Extra Config: 'none'
    pg_hba entries ( '172.16.30.0/24' )
    Extra pg_hba: '172.16.30.0/24', Specific Extra pg_hba: 'none'
Coordinator Master: 
    Nodename: 'coord2', port: 20005, pooler port: 20011
    MaxWalSenders: 5, Dir: '/home/koichi/pgxc/localnodes/coord2'
    ExtraConfig: 'coordExtraConfig', Specific Extra Config: 'none'
    pg_hba entries ( '172.16.30.0/24' )
    Extra pg_hba: '172.16.30.0/24', Specific Extra pg_hba: 'none'
Datanode Master: 
    Nodename: 'datanode1', port: 20008
    MaxWALSenders: 5, Dir: '/home/koichi/pgxc/localnodes/dn1'
    ExtraConfig: 'datanodeExtraConfig', Specific Extra Config: 'none'
    pg_hba entries ( '172.16.30.0/24' )
    Extra pg_hba: 'none', Specific Extra pg_hba: 'none'
Datanode Master: 
    Nodename: 'datanode2', port: 20009
    MaxWALSenders: 5, Dir: '/home/koichi/pgxc/localnodes/dn2'
    ExtraConfig: 'datanodeExtraConfig', Specific Extra Config: 'none'
    pg_hba entries ( '172.16.30.0/24' )
    Extra pg_hba: 'none', Specific Extra pg_hba: 'none'
PGXC psql -p 20005
psql (PGXC 1.2devel, based on PG 9.3.9)
Type "help" for help.

koichi=# show synchronous_commit;
 synchronous_commit 
--------------------
 off
(1 row)

koichi=# \q
PGXC psql -p 20004
psql (PGXC 1.2devel, based on PG 9.3.9)
Type "help" for help.

koichi=# show synchronous_commit;
 synchronous_commit 
--------------------
 off
(1 row)

koichi=# \q
PGXC psql -p 20008
psql (PGXC 1.2devel, based on PG 9.3.9)
Type "help" for help.

koichi=# show synchronous_commit;
 synchronous_commit 
--------------------
 off
(1 row)

koichi=# \q
PGXC psql -p 20009
psql (PGXC 1.2devel, based on PG 9.3.9)
Type "help" for help.

koichi=# show synchronous_commit;
 synchronous_commit 
--------------------
 off
(1 row)

koichi=# \q
PGXC q
[koichi@everest:pgxc_ctl]$
```

**Comment by 249159658** [comment] 2015-08-04 05:56
if synchronous_commit = off ,the datanode will finish local commit quickly.then next update will excute quickly ,and so on.
so the datanode commit  quickly then GTM commit,it is more likely to happen.
when many concurrent updates running,At the same time to execute query time and time again.
as select xmin,xmax,\* from test  where a = 1;  
you need run select many times,and after the updates running,the data is not conflict.

**Comment by koichi-szk** [comment] 2015-08-04 06:03
As I wrote, more than four million transactions ran in the test (both read/write) in ten threads each with full speed.   So the test result indicates current X2 maintains data consistency well.   Should I run the test even more?

**Comment by 249159658** [comment] 2015-08-04 06:12
how do you check the data consistency?
do you excute select time and time again while update running?
or you need run more update threads,i use 20 threads.
In my test environment, it is easy to replicate the problem. Sometimes 2 minutes to perform.

**Comment by koichi-szk** [comment] 2015-08-04 06:17
Konstaintin's integrity test.   It was posted to XL people and Galy forwarded to X2 members.   It runs many conflicting updates.   According to Konstaintin's test, XL showed inconsistent update for about every two thousand updating transactions.   In the case of latest X2, the same test didn't show any inconsistency in more than four million transaction runs.

Please share your test case and your result.   It is quite important to share the raw result.

Please be sure to use the current HEAD of REL1_2_STABLE branch.   Master branch does not contain further PG fixes, while REL1_2_STABLE does, as well as our recent fixes.

Thanx.

**Comment by koichi-szk** [comment] 2015-08-04 06:28
Konstantin's test script is available from my google drive.   Visit https://drive.google.com/file/d/0B88Ktv2MiEWGTUJsdTlUdV9QSDA/view?usp=sharing

**Comment by koichi-szk** [comment] 2015-08-04 09:11
Hi, Mr.249159658;

I ran your script (with two datanodes).  Because there's only one tuple and distribution column value stays the same, I believe there's no difference in the test.

I didn't find any difference when I ran twenty concurrent updates as you did.

Following is the result.   I hope it is okay.

I wonder if you tested against XL.   Yes, XL showed such inconsistency.   As to current HEAD of REL1_2_STABLE, both test passes.

Any further input is welcome.

```
[koichi@everest:another_inconsistency]$ wc log*
  100   200   900 log01
  100   200   900 log02
  100   200   900 log03
  100   200   900 log04
  100   200   900 log05
  100   200   900 log06
  100   200   900 log07
  100   200   900 log08
  100   200   900 log09
  100   200   900 log11
  100   200   900 log12
  100   200   900 log13
  100   200   900 log14
  100   200   900 log15
  100   200   900 log16
  100   200   900 log17
  100   200   900 log18
  100   200   900 log19
  100   200   900 log20
 1900  3800 17100 合計
[koichi@everest:another_inconsistency]$ psql -p 20004
psql (PGXC 1.2devel, based on PG 9.3.9)
Type "help" for help.

koichi=# select * from test;
 a |   b    |   c    
---+--------+--------
 1 | 133900 | 267800
(1 row)

koichi=# \d+ test
                         Table "public.test"
 Column |  Type   | Modifiers | Storage | Stats target | Description 
--------+---------+-----------+---------+--------------+-------------
 a      | integer | not null  | plain   |              | 
 b      | integer |           | plain   |              | 
 c      | integer |           | plain   |              | 
Indexes:
    "test_pkey" PRIMARY KEY, btree (a)
Has OIDs: no
Distribute By: HASH(a)
Location Nodes: ALL DATANODES

koichi=# select xmin,xmax,* from test;
 xmin | xmax | a |   b    |   c    
------+------+---+--------+--------
 6018 |    0 | 1 | 133900 | 267800
(1 row)

koichi=#
```

For details, I used the following scripts:

```
[koichi@everest:another_inconsistency]$ cat init.sql
create table test (a int primary key, b int, c int);

insert into test values (1, 130000, 260000);

select * from test;
[koichi@everest:another_inconsistency]$
```

```
[koichi@everest:another_inconsistency]$ cat test.bash
#!/bin/bash
port=20004
psql -p $port < test.sql > log01 &
psql -p $port < test.sql > log02 &
psql -p $port < test.sql > log03 &
psql -p $port < test.sql > log04 &
psql -p $port < test.sql > log05 &
psql -p $port < test.sql > log06 &
psql -p $port < test.sql > log07 &
psql -p $port < test.sql > log08 &
psql -p $port < test.sql > log09 &
psql -p $port < test.sql > log11 &
psql -p $port < test.sql > log12 &
psql -p $port < test.sql > log13 &
psql -p $port < test.sql > log14 &
psql -p $port < test.sql > log15 &
psql -p $port < test.sql > log16 &
psql -p $port < test.sql > log17 &
psql -p $port < test.sql > log18 &
psql -p $port < test.sql > log19 &
psql -p $port < test.sql > log20 &
[koichi@everest:another_inconsistency]$ 
```

```
[koichi@everest:another_inconsistency]$ cat test.sql
update test set b=b+1,c=c+2 where a=1;
update test set b=b+1,c=c+2 where a=1;

... (100 lines)...

update test set b=b+1,c=c+2 where a=1;
update test set b=b+1,c=c+2 where a=1;
[koichi@everest:another_inconsistency]$ 
```

**Comment by koichi-szk** [comment] 2015-08-04 09:36
I increased number of update to 1000 for each thread and had the same result.   No pkey violation was found.

Further, I ran forty updates in parallel, which was also correct.

```
[koichi@everest:another_inconsistency]$ wc log*
  1000   2000   9000 log01
  1000   2000   9000 log02
  1000   2000   9000 log03
  1000   2000   9000 log04
  1000   2000   9000 log05
  1000   2000   9000 log06
  1000   2000   9000 log07
  1000   2000   9000 log08
  1000   2000   9000 log09
  1000   2000   9000 log11
  1000   2000   9000 log12
  1000   2000   9000 log13
  1000   2000   9000 log14
  1000   2000   9000 log15
  1000   2000   9000 log16
  1000   2000   9000 log17
  1000   2000   9000 log18
  1000   2000   9000 log19
  1000   2000   9000 log20
 19000  38000 171000 合計
[koichi@everest:another_inconsistency]$ psql -p 20004
psql (PGXC 1.2devel, based on PG 9.3.9)
Type "help" for help.

koichi=# select * from test;
 a |   b    |   c    
---+--------+--------
 1 | 152900 | 305800
(1 row)

koichi=# select xmin,xmax,* from test;
 xmin  | xmax | a |   b    |   c    
-------+------+---+--------+--------
 25210 |    0 | 1 | 152900 | 305800
(1 row)

koichi=#
```

```
[koichi@everest:another_inconsistency]$ wc log*
  1000   2000   9000 log01
  1000   2000   9000 log02
  1000   2000   9000 log03
  1000   2000   9000 log04
  1000   2000   9000 log05
  1000   2000   9000 log06
  1000   2000   9000 log07
  1000   2000   9000 log08
  1000   2000   9000 log09
  1000   2000   9000 log11
  1000   2000   9000 log12
  1000   2000   9000 log13
  1000   2000   9000 log14
  1000   2000   9000 log15
  1000   2000   9000 log16
  1000   2000   9000 log17
  1000   2000   9000 log18
  1000   2000   9000 log19
  1000   2000   9000 log20
  1000   2000   9000 log21
  1000   2000   9000 log22
  1000   2000   9000 log23
  1000   2000   9000 log24
  1000   2000   9000 log25
  1000   2000   9000 log26
  1000   2000   9000 log27
  1000   2000   9000 log28
  1000   2000   9000 log29
  1000   2000   9000 log30
  1000   2000   9000 log31
  1000   2000   9000 log32
  1000   2000   9000 log33
  1000   2000   9000 log34
  1000   2000   9000 log35
  1000   2000   9000 log36
  1000   2000   9000 log37
  1000   2000   9000 log38
  1000   2000   9000 log39
  1000   2000   9000 log40
 39000  78000 351000 合計
[koichi@everest:another_inconsistency]$ psql -p 20004
psql (PGXC 1.2devel, based on PG 9.3.9)
Type "help" for help.

koichi=# select * from test;
 a |   b    |   c    
---+--------+--------
 1 | 191900 | 383800
(1 row)

koichi=# select xmin,xmax,* from test;
 xmin  | xmax | a |   b    |   c    
-------+------+---+--------+--------
 64435 |    0 | 1 | 191900 | 383800
(1 row)

koichi=#
```

**Comment by 249159658** [comment] 2015-08-04 11:37
do you excute select time and time again        !!!while!!!    update running?

Sorry, I didn't say clearly reproduction method.  
you need excute   select xmin,xmax,\* from test;  while the update is running.
not after the update is done.

**Comment by 249159658** [comment] 2015-08-04 11:40
you can use psql excute "select xmin,xmax,\* from test;select xmin,xmax,\* from test;select xmin,xmax,\* from test;select xmin,xmax,\* from test;"  one time.
need excute many times.

**Comment by koichi-szk** [comment] 2015-08-04 14:16
Thanks.   With concurrent read while concurrent update, I found more than one tuple visible.   Okay, this must be the issue.   I will run the same test with my candidate fix tomorrow.

**Comment by koichi-szk** [comment] 2015-08-05 04:33
The test with the latest fix patch worked well.    The fix should go to all the relevant branches, master, REL1_2_STABLE and REL1_1_STABLE.

**Comment by koichi-szk** [comment] 2015-08-05 05:02
Committed
master: 2341c8c285fea7d8235424a4a357d93837b2b67a
REL1_2_STABLE: d79f5f06b54043d0aa18e7a276589d777584b9cb
REL1_1_STABLE: b85b75c7d2dda796d294559cb32a39f28d365653

#256 will be closed too.

**Closed as completed by koichi-szk** 2015-08-05 05:02 UTC
Labels: bug, duplicate
